version: "2.4"

services:
   home-assistant:
      extends:
         service: home-assistant
         file: home-assistant/docker-compose.yaml
      networks:
         docker_vlan:
            ipv4_address: 10.10.10.200
      depends_on:
         mqtt:
            condition: service_started

   mqtt:
      extends:
         service: mqtt
         file: mqtt/docker-compose.yaml
      networks:
         docker_vlan:
            ipv4_address: 10.10.10.199
 
networks:
   docker_vlan:
      driver: macvlan
      driver_opts:
         parent: ovs_eth0
      ipam:
         config:
              - subnet: 10.10.10.0/24
                gateway: 10.10.10.1

# vim: set ts=3 sw=3 et:
