version: "2"

services:
   mqtt:
      image: eclipse-mosquitto:latest
      container_name: mqtt
      restart: always
      network_mode: host
      ports:
        - 1883/tcp
      volumes:
        - ./config:/config
      healthcheck:
        test: ["CMD-SHELL", "timeout 5 mosquitto_sub -t '$$SYS/#' -C 1 | grep -v Error || exit 1"]
        interval: 30s
        timeout: 10s
        retries: 6
