version: "2.4"

services:
  home-assistant:
     container_name: home-assistant
     image: retsamedoc/home-assistant
     privileged: false
     restart: unless-stopped
     hostname: homeassistant
     domainname: digitalactionsproject.org
     mem_limit: 512m
     mac_address: 02:42:c0:de:ad:01
     cap_add:
        - NET_ADMIN
     ports:
        - 80/tcp
        - 443/tcp
        - 8123/tcp
     volumes:
        - ./config:/config
     environment:
        TZ: America/Phoenix
     healthcheck:
        test: ["CMD", "curl", "-f", "http://127.0.0.1:8123"]
        interval: 30s
        timeout: 10s
        retries: 6
     logging:
        options:
           max-size: "10m"
           max-file: "3"

# vim: set ts=3 sw=3 et:
