version: "2"

services:
  homeassistant:
     conatiner_name: homeassistant
     image: retsamedoc/homeassistant:latest
     privileged: false
     restart: unless-stopped
     hostname: homeassistant
     domainname: digitalactionsproject.org
     mac_address: 02:42:c0:de:ad:01
     cap_add:
        - NET_ADMIN
     ports:
        - 80/tcp
        - 443/tcp
        - 8123/tcp
     volumes:
        - config/home-assistant:/config
     environment:
        TZ: America/Phoenix
     depends_on:
        mqtt:
           condition: service_started
     healthcheck:
        test: ["CMD", "curl", "-f", "http://127.0.0.1:8123"]
        interval: 30s
        timeout: 10s
        retries: 6
     logging:
        options:
           max-size: "10m"
           max-file: "3"

