version: "2"

services:
   ring-alarm:
      image: retsamedoc/ring-alarm-mqtt:latest
      container_name: ring-alarm
      restart: always
      network_mode: host
      ports:
        - 55123/tcp
      volumes:
        - ./config:/etc/ring-mqtt
      environment:
        - TZ: America/Phoenix
      env_file:
        - ./.env

#
# vim: set ts=3 sw=3 et:
